apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-07-03T17:11:36Z"
  generateName: capi-controller-manager-6d9b75ccdc-
  labels:
    app.kubernetes.io/managed-by: tilt
    cluster.x-k8s.io/provider: cluster-api
    control-plane: controller-manager
    pod-template-hash: 6d9b75ccdc
    tilt.dev/pod-template-hash: aabc68588a12959d4f41
  name: capi-controller-manager-6d9b75ccdc-pvxln
  namespace: capi-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: capi-controller-manager-6d9b75ccdc
    uid: ab5b2206-c718-451e-a277-2ec4a955c1c0
  resourceVersion: "1663"
  uid: fecee7c0-49f3-4694-902f-d9d7ea2cbfb5
spec:
  containers:
  - args:
    - --leader-elect
    - --metrics-bind-addr=0.0.0.0:8080
    - --feature-gates=MachinePool=false,ClusterResourceSet=false,ClusterTopology=false,RuntimeSDK=false,MachineSetPreflightChecks=false
    command:
    - sh
    - /start.sh
    - /manager
    env:
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: POD_UID
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.uid
    image: docker.io/cahillsf/cluster-api-controller-amd64:dev
    imagePullPolicy: Always
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /healthz
        port: healthz
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    name: manager
    ports:
    - containerPort: 9443
      name: webhook-server
      protocol: TCP
    - containerPort: 9440
      name: healthz
      protocol: TCP
    - containerPort: 8080
      name: metrics
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /readyz
        port: healthz
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /tmp/k8s-webhook-server/serving-certs
      name: cert
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-zhhwx
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: capi-test-control-plane
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: capi-manager
  serviceAccountName: capi-manager
  terminationGracePeriodSeconds: 10
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: cert
    secret:
      defaultMode: 420
      secretName: capi-webhook-service-cert
  - name: kube-api-access-zhhwx
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-07-03T17:11:36Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-07-03T17:11:36Z"
    message: 'containers with unready status: [manager]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-07-03T17:11:36Z"
    message: 'containers with unready status: [manager]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-07-03T17:11:36Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://644815f2fc9521389c4ba02ec093f588f919d645f880daffb20a3dd336459b55
    image: docker.io/cahillsf/cluster-api-controller-amd64:dev
    imageID: docker.io/cahillsf/cluster-api-controller-amd64@sha256:7b25e440a8587f5edaa704088bc9de9d7610e14132f5c192931a0c72ee633d94
    lastState:
      terminated:
        containerID: containerd://644815f2fc9521389c4ba02ec093f588f919d645f880daffb20a3dd336459b55
        exitCode: 128
        finishedAt: "2023-07-03T17:15:26Z"
        message: 'failed to create containerd task: failed to create shim task: OCI
          runtime create failed: runc create failed: unable to start container process:
          exec: "sh": executable file not found in $PATH: unknown'
        reason: StartError
        startedAt: "1970-01-01T00:00:00Z"
    name: manager
    ready: false
    restartCount: 5
    started: false
    state:
      waiting:
        message: back-off 2m40s restarting failed container=manager pod=capi-controller-manager-6d9b75ccdc-pvxln_capi-system(fecee7c0-49f3-4694-902f-d9d7ea2cbfb5)
        reason: CrashLoopBackOff
  hostIP: 172.18.0.3
  phase: Running
  podIP: 10.244.0.11
  podIPs:
  - ip: 10.244.0.11
  - ip: fd00:10:244::b
  qosClass: BestEffort
  startTime: "2023-07-03T17:11:36Z"
